tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "nikitabobko/tap"
tap "sdkman/tap"
# Run your GitHub Actions locally
brew "act"
# JPEG image codec that aids compression and decompression
brew "jpeg-turbo"
# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Dependency manager for Cocoa projects
brew "cocoapods"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# Tool for exploring each layer in a docker image
brew "dive"
# View disk space usage and delete unwanted data, fast
brew "dua-cli"
# Easiest way to build and release mobile apps
brew "fastlane"
# Multi-format archive and compression library
brew "libarchive"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Command-line benchmarking tool
brew "hyperfine"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Terraform version manager inspired by rbenv
brew "tfenv"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vulnerability scanner for container images, file systems, and Git repos
brew "trivy"
# Watch files and take action when they change
brew "watchman"
# JavaScript package manager
brew "yarn"
# SDKMAN! the Software Development Kit Manager
brew "sdkman/tap/sdkman-cli"
# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace"
# AI-powered productivity tool for the command-line
cask "amazon-q"
# Android SDK component
cask "android-platform-tools"
# Tools for building Android applications
cask "android-studio"
# Cross platform SQL editor and database management app
cask "beekeeper-studio"
# Desktop password and login vault
cask "bitwarden"
# Open source IDE for exploring and testing APIs
cask "bruno"
# Anthropic's official Claude AI desktop app
cask "claude"
# Write, edit, and chat about your code with AI
cask "cursor"
# Database manager
cask "dataflare"
# App to build and share containerised applications and microservices
cask "docker"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-cascadia-code"
cask "font-jetbrains-mono"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Utility to hide menu bar items
cask "hiddenbar"
# Open-source screen recorder built with web technology
cask "kap"
# Open-source keystroke visualiser
cask "keycastr"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Discover, download, and run local LLMs
cask "lm-studio"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Reverse proxy that enables you to expose your localhost to the internet
cask "localxpose"
# Clipboard manager
cask "maccy"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Multi-platform web browser
cask "microsoft-edge"
# Remote desktop client
cask "microsoft-remote-desktop"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Interactive tool for analyzing MongoDB data
cask "mongodb-compass"
# WiFi site survey software and WiFi scanner
cask "netspot"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Cloud storage client
cask "onedrive"
# Replacement for Docker Desktop
cask "orbstack"
# Collaboration platform for API development
cask "postman"
# HTTP debugging proxy
cask "proxyman"
# Control your tools with a few keystrokes
cask "raycast"
# Email client
cask "readdle-spark"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Open source virtual/remote desktop application
cask "rustdesk"
# Team communication and collaboration software
cask "slack"
# Application to control your PlayStation 4 or PlayStation 5
cask "sony-ps-remote-play"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Native GUI tool for relational databases
cask "tableplus"
# Customizable email client
cask "thunderbird"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Multiplayer code editor
cask "zed"
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Medis", id: 1579200037
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
